import sys
import os
import filecmp
import shutil
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
os.chdir(PROJECT_ROOT / "Test_Cases")

# Add parent directory to path for imports
sys.path.insert(0, str(PROJECT_ROOT))

from solutions.Nik_soln import Code_Problems as SolutionProblems
from practice.code_problems import Code_Problems as PracticeProblems

# Create temporary directories for solution and practice outputs
SOLUTION_GEN_DIR = PROJECT_ROOT / "generated_files_solution"
PRACTICE_GEN_DIR = PROJECT_ROOT / "generated_files_practice"

os.makedirs(SOLUTION_GEN_DIR, exist_ok=True)
os.makedirs(PRACTICE_GEN_DIR, exist_ok=True)

# Initialize both classes
solution = SolutionProblems()
practice = PracticeProblems()

# Clean generated files directories at start
temp_gen_dir = PROJECT_ROOT / "generated_files"
if os.path.exists(temp_gen_dir):
    shutil.rmtree(temp_gen_dir)
os.makedirs(temp_gen_dir, exist_ok=True)
shutil.rmtree(SOLUTION_GEN_DIR, ignore_errors=True)
shutil.rmtree(PRACTICE_GEN_DIR, ignore_errors=True)
os.makedirs(SOLUTION_GEN_DIR, exist_ok=True)
os.makedirs(PRACTICE_GEN_DIR, exist_ok=True)

# Track results
results = {
    "passed": [],
    "failed": [],
    "file_comparisons": [],
    "errors": []
}

def compare_results(problem_num, solution_result, practice_result):
    """Compare returns from both implementations - check type and value"""
    solution_type = type(solution_result).__name__
    practice_type = type(practice_result).__name__
    
    # Check if types match
    if solution_type != practice_type:
        return False, f"[FAIL] Problem {problem_num}: Type mismatch\n  Solution type: {solution_type} = {solution_result}\n  Practice type: {practice_type} = {practice_result}"
    
    # Check if values match
    if solution_result != practice_result:
        return False, f"[FAIL] Problem {problem_num}: Value mismatch\n  Solution ({solution_type}): {solution_result}\n  Practice ({practice_type}): {practice_result}"
    
    return True, f"[PASS] Problem {problem_num}: Results match (type: {solution_type})"

def compare_files(problem_num, filename):
    """Dynamically compare generated files if they exist"""
    solution_file = SOLUTION_GEN_DIR / filename
    practice_file = PRACTICE_GEN_DIR / filename
    
    try:
        solution_exists = os.path.exists(solution_file)
        practice_exists = os.path.exists(practice_file)
        
        if not solution_exists and not practice_exists:
            return None, f"[SKIP] Problem {problem_num}: File '{filename}' not generated by either implementation"
        elif not solution_exists:
            return None, f"[SKIP] Problem {problem_num}: Solution file not found: {filename}"
        elif not practice_exists:
            return None, f"[SKIP] Problem {problem_num}: Practice file not found: {filename}"
        else:
            # Both files exist, compare them
            if filecmp.cmp(solution_file, practice_file, shallow=False):
                return True, f"[PASS] Problem {problem_num}: Generated files match"
            else:
                return False, f"[FAIL] Problem {problem_num}: Generated files differ"
    except Exception as e:
        return None, f"[ERROR] Problem {problem_num}: Could not compare files - {e}"

# Problem configurations: (problem_num, args, kwargs, generated_file)
# generated_file is the filename expected in the generated_files directory
# Problems with parameters have multiple test cases (original + 3 alternatives)
test_configs = [
    (1, (), {}, None),
    (2, (), {}, None),
    (3, (), {}, None),
    (4, (), {}, "grades_output.csv"),
    (5, (), {}, "output.csv"),
    (6, (), {}, None),
    # Problem 7: Random number generation - (num_integers, max_bound)
    (7, (10, 50), {}, "recur.txt"),  # Original
    (7, (5, 20), {}, "recur.txt"),   # Alt 1: Smaller set
    (7, (15, 100), {}, "recur.txt"), # Alt 2: Larger set
    (7, (8, 10), {}, "recur.txt"),   # Alt 3: Medium set
    (8, (), {}, "recur2.txt"),
    # Problem 9: Binary search - target value
    (9, (10,), {}, None),            # Original
    (9, (3,), {}, None),             # Alt 1: Smaller number
    (9, (15,), {}, None),            # Alt 2: Larger number
    (9, (1,), {}, None),             # Alt 3: Minimum value
    # Problem 10: Golden ratio - (starting_guess, tolerance)
    (10, (1.5, 0.0001), {}, None),   # Original
    (10, (2.0, 0.001), {}, None),    # Alt 1: Different starting guess
    (10, (1.0, 0.00001), {}, None),  # Alt 2: Tighter tolerance
    (10, (3.0, 0.01), {}, None),     # Alt 3: Higher guess, looser tolerance
    # Problem 11: Recursive Fibonacci - (n)
    (11, (10,), {}, None),           # Original
    (11, (5,), {}, None),            # Alt 1: Smaller n
    (11, (15,), {}, None),           # Alt 2: Larger n
    (11, (7,), {}, None),            # Alt 3: Medium n
    # Problem 12: Iterative Fibonacci - (n)
    (12, (10,), {}, None),           # Original
    (12, (25,), {}, None),           # Alt 1: Larger n
    (12, (30,), {}, None),           # Alt 2: Even larger n
    (12, (20,), {}, None),           # Alt 3: Medium-large n
    (13, (), {}, None),
    # Problem 14: Generate random integer rows - (num_rows)
    (14, (5,), {}, "recur2.txt"),    # Original
    (14, (3,), {}, "recur2.txt"),    # Alt 1: Fewer rows
    (14, (8,), {}, "recur2.txt"),    # Alt 2: More rows
    (14, (2,), {}, "recur2.txt"),    # Alt 3: Minimal rows
    (15, (), {}, "recur3.txt"),
    (16, (), {}, None),
    # Problem 17: House area - (num_storeys, dimensions_list, roof_height)
    (17, (2, [10, 8, 12], 5), {}, None),      # Original
    (17, (1, [15, 20, 10], 6), {}, None),     # Alt 1: Single storey
    (17, (3, [8, 8, 8], 4), {}, None),        # Alt 2: Three storeys
    (17, (2, [12, 18, 9], 7), {}, None),      # Alt 3: Rectangular house
    (18, (), {}, None),
    # Problem 19: Encode passage - (text_string)
    (19, ("Hello World",), {}, None),         # Original
    (19, ("The quick brown fox",), {}, None), # Alt 1: Longer phrase
    (19, ("A",), {}, None),                   # Alt 2: Single character
    (19, ("Python 123",), {}, None),          # Alt 3: With numbers
    (20, (), {}, None),
    # Problem 21: Multiplication using addition - (num1, num2)
    (21, (3, 5), {}, None),                   # Original
    (21, (7, 8), {}, None),                   # Alt 1: 7 * 8
    (21, (2, 10), {}, None),                  # Alt 2: 2 * 10
    (21, (6, 6), {}, None),                   # Alt 3: 6 * 6
    (22, (), {}, None),
    (23, (), {}, None),
    # Problem 24: Remove vowels from string - (text_string)
    (24, ("hello world",), {}, None),                        # Original
    (24, ("The quick brown fox jumps",), {}, None),          # Alt 1: Multiple words
    (24, ("aeiou",), {}, None),                              # Alt 2: All vowels
    (24, ("xyz",), {}, None),                                # Alt 3: No vowels
    # Problem 25: Vehicle class - (list_of_vehicle_data)
    (25, ([["jimmy", "honda", "civic", 2010, "red"]],), {}, None),  # Original
    (25, ([["Alice", "toyota", "camry", 2015, "blue"], ["Bob", "harley", "sportster", 2020, "black"]],), {}, None),  # Alt 1
    (25, ([["Carol", "mercedes", "bus", 2018, "yellow"]],), {}, None),   # Alt 2: Single bus
    (25, ([["David", "ford", "f150", 2022, "white"], ["Eve", "honda", "civic", 2019, "green"], ["Frank", "chevy", "silverado", 2010, "gray"]],), {}, None),  # Alt 3
    # Problem 26: Vehicle class with error handling - (list_of_vehicle_data)
    (26, ([["jimmy", "honda", "civic", '2010x', "red"]],), {}, None),  # Original
    (26, ([["Gray", "invalid", "boat", 2020, "blue"], ["Henry", "ford", "car", 2021, "red"]],), {}, None),  # Alt 1: Invalid type
    (26, ([["Ivy", "tesla", "car", 2030, "orange"]],), {}, None),     # Alt 2: Future year
    (26, ([["Jack", "chevy", "truck", "abc", "purple"], ["Kim", "mercedes", "bus", 2012, "silver"]],), {}, None),  # Alt 3: Non-int year
    (27, (), {}, None),
    # Problem 28: Scope with ping_pong counter - (list_of_integers)
    (28, ([1, 2, 3, 2, 1],), {}, None),       # Original
    (28, ([1, 3, 2, 4],), {}, None),          # Alt 1: All increases then one decrease
    (28, ([5, 4, 3, 2, 1],), {}, None),       # Alt 2: Completely descending
    (28, ([1, 1, 1, 1],), {}, None),          # Alt 3: All same values
    (29, (), {}, None),
    (30, (), {}, None),
    (31, (), {}, None),
    (32, (), {}, None),
    (33, (), {}, None),
    (34, (), {}, None),
    (35, (), {}, None),
    (36, (), {}, None),
    (37, (), {}, None),
    (38, (), {}, None),
    (39, (), {}, None),
    (40, (), {}, None),
    (41, (), {}, None),
    (42, (), {}, None),
]

print("=" * 80)
print("COMPARING SOLUTIONS VS PRACTICE IMPLEMENTATIONS")
print("(42 problems + 39 alternative test cases = 81 total test cases)")
print("=" * 80)

# Suppress individual test output - only show summary
import sys
import io

# Redirect stdout during tests to suppress individual messages
test_output = io.StringIO()
original_stdout = sys.stdout
sys.stdout = test_output

# Track failed test details for verbose output
failed_details = []

# Run all tests
import time

for config in test_configs:
    problem_num = config[0]
    args = config[1]
    kwargs = config[2]
    generated_file = config[3] if len(config) > 3 else None
    
    try:
        # Get the current state of generated_files before running
        temp_gen_dir = PROJECT_ROOT / "generated_files"
        os.makedirs(temp_gen_dir, exist_ok=True)
        
        # Get pre-solution state
        pre_solution_state = {}
        if os.path.exists(temp_gen_dir):
            for file in os.listdir(temp_gen_dir):
                file_path = os.path.join(temp_gen_dir, file)
                if os.path.isfile(file_path):
                    pre_solution_state[file] = os.path.getmtime(file_path)
        
        # Run solution implementation
        solution_result = solution.run_problem(problem_num, *args, **kwargs)
        time.sleep(0.1)  # Small delay to ensure file timestamps differ
        
        # Copy new/modified files from solution
        if os.path.exists(temp_gen_dir):
            for file in os.listdir(temp_gen_dir):
                file_path = os.path.join(temp_gen_dir, file)
                if os.path.isfile(file_path):
                    # Check if file is new or modified
                    if file not in pre_solution_state or os.path.getmtime(file_path) > pre_solution_state[file]:
                        dst = SOLUTION_GEN_DIR / file
                        shutil.copy2(file_path, dst)
        
        # Get post-solution state for practice
        pre_practice_state = {}
        if os.path.exists(temp_gen_dir):
            for file in os.listdir(temp_gen_dir):
                file_path = os.path.join(temp_gen_dir, file)
                if os.path.isfile(file_path):
                    pre_practice_state[file] = os.path.getmtime(file_path)
        
        # Run practice implementation
        practice_result = practice.run_problem(problem_num, *args, **kwargs)
        time.sleep(0.1)  # Small delay
        
        # Copy new/modified files from practice
        if os.path.exists(temp_gen_dir):
            for file in os.listdir(temp_gen_dir):
                file_path = os.path.join(temp_gen_dir, file)
                if os.path.isfile(file_path):
                    # Check if file is new or modified during practice run
                    if file not in pre_practice_state or os.path.getmtime(file_path) > pre_practice_state[file]:
                        dst = PRACTICE_GEN_DIR / file
                        shutil.copy2(file_path, dst)
        
        # Compare results
        match, message = compare_results(problem_num, solution_result, practice_result)
        
        if match:
            results["passed"].append(problem_num)
            print(message)
        else:
            results["failed"].append(problem_num)
            failed_details.append((problem_num, args, message))
            print(message)
        
        # Compare generated files if specified
        if generated_file:
            file_match, file_message = compare_files(problem_num, generated_file)
            # Always print file comparison messages (including SKIPs)
            print(f"  {file_message}")
            # Track actual pass/fail results (not SKIPs)
            if file_match is not None:
                results["file_comparisons"].append((problem_num, file_match))
            
    except Exception as e:
        results["errors"].append((problem_num, str(e)))
        print(f"[ERROR] Problem {problem_num}: {e}")

# Restore stdout
sys.stdout = original_stdout

# Summary
summary_lines = []
summary_lines.append("=" * 80)
total_tests = len(test_configs)
summary_lines.append(f"[PASS] Passed: {len(results['passed'])}/{total_tests}")
summary_lines.append(f"[FAIL] Failed: {len(results['failed'])}/{total_tests}")
summary_lines.append(f"[ERROR] Errors: {len(results['errors'])}/{total_tests}")

if results["failed"]:
    failed_unique = sorted(set(results['failed']))
    summary_lines.append(f"\nFailed problems: {failed_unique}")

if results["errors"]:
    errors_unique = sorted(set([p for p, _ in results['errors']]))
    summary_lines.append(f"\nProblems with errors: {errors_unique}")

# Add detailed failure info
if failed_details:
    summary_lines.append("\n" + "=" * 80)
    summary_lines.append("FAILURE DETAILS (first 5 failures):")
    summary_lines.append("=" * 80)
    for problem_num, args, message in failed_details[:5]:
        summary_lines.append(f"\n{message}")
        summary_lines.append(f"  Args: {args}")

summary_lines.append("\n" + "=" * 80)

# Print to console
for line in summary_lines:
    print(line)

# Append to history.txt
history_path = PROJECT_ROOT / "history.txt"
if not history_path.exists():
    with open(history_path, 'w') as f:
        pass
    
with open(history_path, 'a') as f:
    for line in summary_lines:
        f.write(line + '\n')
